N = 20;
D = 1; 
eigE=zeros(length(mu),2*N);

figure(1), ...
    t = 1;
    mu = linspace(-3*t,3*t,1001); 
    for k = 1:length(mu)
        Em=[-mu(k) 0; 0 mu(k)];
        Tm=[-t -D; D t];
    
        Hkc = kron(diag(ones(1,N)),Em)... 
            +kron(diag(ones(1,N-1),1),Tm)...
            +kron(diag(ones(1,N-1),-1),Tm');
    
        [Vxx,Dxx] = eig(Hkc);
        eigE(k,:) = diag(Dxx);
    end
    subplot(1,3,1),...
        plot(mu/t, eigE/D, 'b'), grid on,...
            xlabel('mu/t'), ylabel('E/D'),...
            legend ('t/D = 1','Location',...
        'northwest');
    t = 3;
    mu = linspace(-3*t,3*t,1001); 
    for k = 1:length(mu)
        Em=[-mu(k) 0; 0 mu(k)];
        Tm=[-t -D; D t];
    
        Hkc = kron(diag(ones(1,N)),Em)... 
            +kron(diag(ones(1,N-1),1),Tm)...
            +kron(diag(ones(1,N-1),-1),Tm');
    
        [Vxx,Dxx] = eig(Hkc);
        eigE(k,:) = diag(Dxx);
    end
    subplot(1,3,2),...
        plot(mu/t, eigE/D, 'b'), grid on,...
            xlabel('mu/t'), ylabel('E/D'),...
            legend ('t/D = 3','Location',...
        'northwest');
    t = 5;
    mu = linspace(-3*t, 3*t,1001); 
    for k = 1:length(mu)
        Em=[-mu(k) 0; 0 mu(k)];
        Tm=[-t -D; D t];
    
        Hkc = kron(diag(ones(1,N)),Em)... 
            +kron(diag(ones(1,N-1),1),Tm)...
            +kron(diag(ones(1,N-1),-1),Tm');
    
        [Vxx,Dxx] = eig(Hkc);
        eigE(k,:) = diag(Dxx);
    end
    subplot(1,3,3),...
        plot(mu/t, eigE/D, 'b'), grid on,...
            xlabel('mu/t'), ylabel('E/D'),...
            legend ('t/D = 5','Location',...
        'northwest');
